#!/usr/bin/env ruby

require 'pry'

$:.unshift(File.expand_path(File.join(File.dirname(__FILE__), "..", "lib")))

#require 'edld'

Pry.config.prompt = [proc { "edld> " }, proc { "EDLD| " }]
Pry.start
